import { Weights, Player } from "./scoring";

// Real 2024-25 Premier League season data (goals, assists, minutes,
// creativity, influence, threat, FPL price) — source: the public
// vaastav/Fantasy-Premier-League dataset, which mirrors the official
// Fantasy Premier League API. Used as the offline fallback pool of
// realistic transfer targets when Supabase isn't connected.
// Generated by generate-real-data.cjs — regenerate with
// `node generate-real-data.cjs` after editing the RAW stats above.
// This also produces supabase/seed.sql from the same source data.
// See lib/supabaseClient.ts (isSupabaseConfigured) and lib/db.ts.

export const POSITIONS = {
  DEF: "Defender",
  MID: "Midfielder",
  FWD: "Forward",
} as const;

export type PositionKey = keyof typeof POSITIONS;

interface ClubDef {
  name: string;
  weights: Record<PositionKey, Weights>;
}

export const CLUBS: Record<string, ClubDef> = {
  arsenal: {
    name: "Arsenal",
    weights: {
      DEF: { creativity: 25, threat: 0, influence: 35, productivity: 10, reliability: 30 },
      MID: { creativity: 40, threat: 5, influence: 25, productivity: 15, reliability: 15 },
      FWD: { creativity: 20, threat: 25, influence: 20, productivity: 25, reliability: 10 },
    },
  },
  liverpool: {
    name: "Liverpool",
    weights: {
      DEF: { creativity: 5, threat: 20, influence: 35, productivity: 15, reliability: 25 },
      MID: { creativity: 20, threat: 25, influence: 25, productivity: 20, reliability: 10 },
      FWD: { creativity: 0, threat: 45, influence: 20, productivity: 30, reliability: 5 },
    },
  },
  mancity: {
    name: "Manchester City",
    weights: {
      DEF: { creativity: 30, threat: 0, influence: 35, productivity: 5, reliability: 30 },
      MID: { creativity: 45, threat: 5, influence: 25, productivity: 10, reliability: 15 },
      FWD: { creativity: 25, threat: 25, influence: 20, productivity: 20, reliability: 10 },
    },
  },
  manutd: {
    name: "Manchester United",
    weights: {
      DEF: { creativity: 5, threat: 20, influence: 30, productivity: 20, reliability: 25 },
      MID: { creativity: 20, threat: 25, influence: 20, productivity: 25, reliability: 10 },
      FWD: { creativity: 0, threat: 45, influence: 15, productivity: 35, reliability: 5 },
    },
  },
  chelsea: {
    name: "Chelsea",
    weights: {
      DEF: { creativity: 15, threat: 15, influence: 25, productivity: 25, reliability: 20 },
      MID: { creativity: 30, threat: 20, influence: 15, productivity: 30, reliability: 5 },
      FWD: { creativity: 10, threat: 40, influence: 10, productivity: 40, reliability: 0 },
    },
  },
};

export const PLAYERS: Record<PositionKey, Player[]> = {
  DEF: [
    { name: "W. Saliba", cost: 6.4, stats: { creativity: 12, threat: 18, influence: 58, productivity: 16, reliability: 84 } },
    { name: "Gabriel Magalhães", cost: 6.1, stats: { creativity: 19, threat: 53, influence: 48, productivity: 50, reliability: 54 } },
    { name: "Virgil van Dijk", cost: 6.7, stats: { creativity: 19, threat: 55, influence: 89, productivity: 28, reliability: 96 } },
    { name: "Trent Alexander-Arnold", cost: 7.2, stats: { creativity: 100, threat: 49, influence: 64, productivity: 100, reliability: 54 } },
    { name: "Joško Gvardiol", cost: 6.5, stats: { creativity: 57, threat: 95, influence: 79, productivity: 36, reliability: 94 } },
    { name: "Rúben Dias", cost: 5.5, stats: { creativity: 15, threat: 25, influence: 35, productivity: 0, reliability: 50 } },
    { name: "Marc Cucurella", cost: 5.4, stats: { creativity: 38, threat: 67, influence: 58, productivity: 55, reliability: 81 } },
    { name: "Marc Guéhi", cost: 4.7, stats: { creativity: 23, threat: 45, influence: 77, productivity: 39, reliability: 84 } },
    { name: "Milos Kerkez", cost: 5.3, stats: { creativity: 75, threat: 43, influence: 61, productivity: 57, reliability: 96 } },
    { name: "Ezri Konsa", cost: 4.5, stats: { creativity: 9, threat: 28, influence: 42, productivity: 16, reliability: 79 } },
    { name: "Pau Torres", cost: 4.2, stats: { creativity: 3, threat: 16, influence: 20, productivity: 0, reliability: 40 } },
    { name: "Matty Cash", cost: 4.4, stats: { creativity: 16, threat: 29, influence: 21, productivity: 23, reliability: 42 } },
    { name: "Lucas Digne", cost: 4.4, stats: { creativity: 68, threat: 18, influence: 39, productivity: 50, reliability: 54 } },
    { name: "Adam Smith", cost: 4.4, stats: { creativity: 12, threat: 0, influence: 0, productivity: 0, reliability: 21 } },
    { name: "Marcos Senesi", cost: 4.6, stats: { creativity: 3, threat: 3, influence: 11, productivity: 0, reliability: 0 } },
    { name: "Nathan Collins", cost: 4.6, stats: { creativity: 13, threat: 57, influence: 100, productivity: 62, reliability: 100 } },
    { name: "Ethan Pinnock", cost: 4.4, stats: { creativity: 6, threat: 34, influence: 43, productivity: 25, reliability: 35 } },
    { name: "Lewis Dunk", cost: 4.2, stats: { creativity: 7, threat: 21, influence: 29, productivity: 11, reliability: 42 } },
    { name: "Pervis Estupiñán", cost: 4.9, stats: { creativity: 61, threat: 30, influence: 38, productivity: 20, reliability: 56 } },
    { name: "Jan Paul van Hecke", cost: 4.5, stats: { creativity: 26, threat: 32, influence: 66, productivity: 16, reliability: 80 } },
    { name: "Daniel Muñoz", cost: 5.2, stats: { creativity: 74, threat: 100, influence: 75, productivity: 73, reliability: 92 } },
    { name: "Tyrick Mitchell", cost: 4.8, stats: { creativity: 65, threat: 29, influence: 53, productivity: 46, reliability: 86 } },
    { name: "James Tarkowski", cost: 4.7, stats: { creativity: 17, threat: 39, influence: 80, productivity: 16, reliability: 79 } },
    { name: "Vitalii Mykolenko", cost: 4.4, stats: { creativity: 48, threat: 15, influence: 52, productivity: 31, reliability: 85 } },
    { name: "Jarrad Branthwaite", cost: 4.9, stats: { creativity: 0, threat: 21, influence: 53, productivity: 9, reliability: 61 } },
    { name: "Calvin Bassey", cost: 4.5, stats: { creativity: 5, threat: 27, influence: 48, productivity: 8, reliability: 85 } },
    { name: "Antonee Robinson", cost: 4.7, stats: { creativity: 86, threat: 36, influence: 88, productivity: 75, reliability: 89 } },
    { name: "Joachim Andersen", cost: 4.2, stats: { creativity: 5, threat: 28, influence: 60, productivity: 0, reliability: 68 } },
    { name: "Wout Faes", cost: 3.8, stats: { creativity: 1, threat: 19, influence: 59, productivity: 8, reliability: 74 } },
    { name: "James Justin", cost: 4.1, stats: { creativity: 26, threat: 36, influence: 52, productivity: 32, reliability: 78 } },
    { name: "Victor Kristiansen", cost: 4.4, stats: { creativity: 39, threat: 3, influence: 40, productivity: 10, reliability: 59 } },
  ],
  MID: [
    { name: "Mohamed Salah", cost: 13.6, stats: { creativity: 81, threat: 100, influence: 100, productivity: 100, reliability: 98 } },
    { name: "Cole Palmer", cost: 10.5, stats: { creativity: 87, threat: 51, influence: 61, productivity: 53, reliability: 89 } },
    { name: "Bruno Fernandes", cost: 8.4, stats: { creativity: 100, threat: 27, influence: 58, productivity: 44, reliability: 81 } },
    { name: "Bukayo Saka", cost: 10.4, stats: { creativity: 50, threat: 40, influence: 26, productivity: 69, reliability: 20 } },
    { name: "Martin Ødegaard", cost: 8.2, stats: { creativity: 61, threat: 22, influence: 20, productivity: 32, reliability: 48 } },
    { name: "Kevin De Bruyne", cost: 9.5, stats: { creativity: 57, threat: 18, influence: 16, productivity: 52, reliability: 18 } },
    { name: "Phil Foden", cost: 9.1, stats: { creativity: 41, threat: 20, influence: 14, productivity: 36, reliability: 22 } },
    { name: "Alexis Mac Allister", cost: 6.2, stats: { creativity: 40, threat: 15, influence: 30, productivity: 25, reliability: 61 } },
    { name: "Dominik Szoboszlai", cost: 6.1, stats: { creativity: 46, threat: 28, influence: 25, productivity: 42, reliability: 56 } },
    { name: "Youri Tielemans", cost: 5.5, stats: { creativity: 61, threat: 14, influence: 41, productivity: 18, reliability: 81 } },
    { name: "John McGinn", cost: 5.2, stats: { creativity: 19, threat: 10, influence: 1, productivity: 10, reliability: 43 } },
    { name: "Morgan Rogers", cost: 5.8, stats: { creativity: 39, threat: 32, influence: 36, productivity: 40, reliability: 86 } },
    { name: "Justin Kluivert", cost: 5.9, stats: { creativity: 33, threat: 37, influence: 33, productivity: 52, reliability: 49 } },
    { name: "Antoine Semenyo", cost: 5.7, stats: { creativity: 36, threat: 59, influence: 40, productivity: 36, reliability: 90 } },
    { name: "Ryan Christie", cost: 4.8, stats: { creativity: 26, threat: 12, influence: 19, productivity: 11, reliability: 38 } },
    { name: "Lewis Cook", cost: 5, stats: { creativity: 40, threat: 2, influence: 26, productivity: 5, reliability: 79 } },
    { name: "Dango Ouattara", cost: 4.5, stats: { creativity: 19, threat: 36, influence: 28, productivity: 35, reliability: 33 } },
    { name: "Keane Lewis-Potter", cost: 5, stats: { creativity: 16, threat: 17, influence: 21, productivity: 7, reliability: 85 } },
    { name: "Bryan Mbeumo", cost: 8.3, stats: { creativity: 73, threat: 52, influence: 74, productivity: 58, reliability: 100 } },
    { name: "Kevin Schade", cost: 5.3, stats: { creativity: 3, threat: 43, influence: 28, productivity: 43, reliability: 46 } },
    { name: "Kaoru Mitoma", cost: 6.3, stats: { creativity: 26, threat: 41, influence: 31, productivity: 37, reliability: 61 } },
    { name: "Yankuba Minteh", cost: 4.8, stats: { creativity: 15, threat: 28, influence: 20, productivity: 39, reliability: 25 } },
    { name: "Georginio Rutter", cost: 5, stats: { creativity: 0, threat: 17, influence: 7, productivity: 44, reliability: 16 } },
    { name: "Eberechi Eze", cost: 7, stats: { creativity: 50, threat: 32, influence: 32, productivity: 40, reliability: 61 } },
    { name: "Ismaïla Sarr", cost: 5.5, stats: { creativity: 30, threat: 42, influence: 31, productivity: 35, reliability: 66 } },
    { name: "Adam Wharton", cost: 4.7, stats: { creativity: 9, threat: 0, influence: 0, productivity: 4, reliability: 0 } },
    { name: "Abdoulaye Doucouré", cost: 5.1, stats: { creativity: 9, threat: 15, influence: 7, productivity: 8, reliability: 59 } },
    { name: "Idrissa Gueye", cost: 4.8, stats: { creativity: 4, threat: 3, influence: 20, productivity: 0, reliability: 83 } },
    { name: "Jack Harrison", cost: 5.2, stats: { creativity: 22, threat: 11, influence: 1, productivity: 7, reliability: 36 } },
    { name: "Dwight McNeil", cost: 5.1, stats: { creativity: 31, threat: 7, influence: 10, productivity: 60, reliability: 2 } },
    { name: "Alex Iwobi", cost: 5.4, stats: { creativity: 57, threat: 33, influence: 41, productivity: 31, reliability: 79 } },
    { name: "Andreas Pereira", cost: 4.9, stats: { creativity: 52, threat: 12, influence: 5, productivity: 23, reliability: 33 } },
    { name: "Emile Smith Rowe", cost: 5, stats: { creativity: 12, threat: 17, influence: 13, productivity: 27, reliability: 34 } },
    { name: "Adama Traoré", cost: 4.5, stats: { creativity: 31, threat: 19, influence: 9, productivity: 36, reliability: 21 } },
    { name: "Stephy Mavididi", cost: 5, stats: { creativity: 8, threat: 12, influence: 6, productivity: 16, reliability: 14 } },
    { name: "Bilal El Khannouss", cost: 4.8, stats: { creativity: 31, threat: 6, influence: 9, productivity: 14, reliability: 41 } },
  ],
  FWD: [
    { name: "Erling Haaland", cost: 14.9, stats: { creativity: 77, threat: 100, influence: 100, productivity: 79, reliability: 92 } },
    { name: "Ollie Watkins", cost: 9.2, stats: { creativity: 73, threat: 73, influence: 79, productivity: 80, reliability: 86 } },
    { name: "Kai Havertz", cost: 7.7, stats: { creativity: 55, threat: 41, influence: 44, productivity: 51, reliability: 54 } },
    { name: "Nicolas Jackson", cost: 7.7, stats: { creativity: 79, threat: 61, influence: 54, productivity: 59, reliability: 70 } },
    { name: "Yoane Wissa", cost: 6.9, stats: { creativity: 86, threat: 76, influence: 89, productivity: 69, reliability: 100 } },
    { name: "Danny Welbeck", cost: 5.5, stats: { creativity: 70, threat: 39, influence: 54, productivity: 58, reliability: 65 } },
    { name: "Jean-Philippe Mateta", cost: 7.5, stats: { creativity: 88, threat: 48, influence: 68, productivity: 47, reliability: 88 } },
    { name: "Raúl Jiménez", cost: 5.3, stats: { creativity: 80, threat: 64, influence: 61, productivity: 47, reliability: 81 } },
    { name: "Rasmus Højlund", cost: 6.9, stats: { creativity: 51, threat: 21, influence: 12, productivity: 11, reliability: 60 } },
    { name: "Jhon Durán", cost: 5.7, stats: { creativity: 7, threat: 14, influence: 22, productivity: 100, reliability: 0 } },
    { name: "Evanilson", cost: 5.9, stats: { creativity: 70, threat: 60, influence: 43, productivity: 52, reliability: 74 } },
    { name: "João Pedro", cost: 5.5, stats: { creativity: 100, threat: 36, influence: 56, productivity: 69, reliability: 58 } },
    { name: "Iliman Ndiaye", cost: 5.2, stats: { creativity: 69, threat: 25, influence: 60, productivity: 23, reliability: 78 } },
    { name: "Dominic Calvert-Lewin", cost: 5.4, stats: { creativity: 20, threat: 31, influence: 13, productivity: 18, reliability: 43 } },
    { name: "Rodrigo Muniz", cost: 5.5, stats: { creativity: 13, threat: 26, influence: 31, productivity: 83, reliability: 14 } },
    { name: "Jamie Vardy", cost: 5.4, stats: { creativity: 55, threat: 44, influence: 47, productivity: 36, reliability: 96 } },
    { name: "Patson Daka", cost: 4.8, stats: { creativity: 0, threat: 0, influence: 0, productivity: 0, reliability: 4 } },
  ],
};
