import { Weights, Player } from "./scoring";

// Real 2024-25 Premier League season data (goals, assists, minutes,
// creativity, influence, threat, FPL price) — source: the public
// vaastav/Fantasy-Premier-League dataset, which mirrors the official
// Fantasy Premier League API. Used as the offline fallback pool of
// realistic transfer targets when Supabase isn't connected.
// Generated by generate-real-data.cjs — regenerate with
// `node generate-real-data.cjs` after editing the RAW stats above.
// This also produces supabase/seed.sql from the same source data.
// See lib/supabaseClient.ts (isSupabaseConfigured) and lib/db.ts.

export const POSITIONS = {
  CB: "Centre-Back",
  FB: "Fullback",
  DM: "Defensive Midfielder",
  CM: "Central Midfielder",
  CAM: "Attacking Midfielder",
  WING: "Winger",
  ST: "Striker",
} as const;

export type PositionKey = keyof typeof POSITIONS;

interface ClubDef {
  name: string;
  weights: Record<PositionKey, Weights>;
}

export const CLUBS: Record<string, ClubDef> = {
  arsenal: {
    name: "Arsenal",
    weights: {
      CB: { creativity: 25, threat: 0, influence: 35, productivity: 10, reliability: 30 },
      FB: { creativity: 35, threat: 0, influence: 25, productivity: 15, reliability: 25 },
      DM: { creativity: 25, threat: 0, influence: 40, productivity: 10, reliability: 30 },
      CM: { creativity: 35, threat: 5, influence: 30, productivity: 15, reliability: 15 },
      CAM: { creativity: 45, threat: 10, influence: 25, productivity: 15, reliability: 5 },
      WING: { creativity: 35, threat: 20, influence: 20, productivity: 20, reliability: 5 },
      ST: { creativity: 20, threat: 25, influence: 20, productivity: 25, reliability: 10 },
    },
  },
  liverpool: {
    name: "Liverpool",
    weights: {
      CB: { creativity: 5, threat: 20, influence: 35, productivity: 15, reliability: 25 },
      FB: { creativity: 15, threat: 20, influence: 25, productivity: 20, reliability: 20 },
      DM: { creativity: 5, threat: 15, influence: 40, productivity: 15, reliability: 25 },
      CM: { creativity: 15, threat: 25, influence: 30, productivity: 20, reliability: 10 },
      CAM: { creativity: 25, threat: 30, influence: 25, productivity: 20, reliability: 0 },
      WING: { creativity: 15, threat: 40, influence: 20, productivity: 25, reliability: 0 },
      ST: { creativity: 0, threat: 45, influence: 20, productivity: 30, reliability: 5 },
    },
  },
  mancity: {
    name: "Manchester City",
    weights: {
      CB: { creativity: 30, threat: 0, influence: 35, productivity: 5, reliability: 30 },
      FB: { creativity: 40, threat: 0, influence: 25, productivity: 10, reliability: 25 },
      DM: { creativity: 30, threat: 0, influence: 40, productivity: 5, reliability: 30 },
      CM: { creativity: 40, threat: 5, influence: 30, productivity: 10, reliability: 15 },
      CAM: { creativity: 50, threat: 10, influence: 25, productivity: 10, reliability: 5 },
      WING: { creativity: 40, threat: 20, influence: 20, productivity: 15, reliability: 5 },
      ST: { creativity: 25, threat: 25, influence: 20, productivity: 20, reliability: 10 },
    },
  },
  manutd: {
    name: "Manchester United",
    weights: {
      CB: { creativity: 5, threat: 20, influence: 30, productivity: 20, reliability: 25 },
      FB: { creativity: 15, threat: 20, influence: 20, productivity: 25, reliability: 20 },
      DM: { creativity: 5, threat: 15, influence: 35, productivity: 20, reliability: 25 },
      CM: { creativity: 15, threat: 25, influence: 25, productivity: 25, reliability: 10 },
      CAM: { creativity: 25, threat: 30, influence: 20, productivity: 25, reliability: 0 },
      WING: { creativity: 15, threat: 40, influence: 15, productivity: 30, reliability: 0 },
      ST: { creativity: 0, threat: 45, influence: 15, productivity: 35, reliability: 5 },
    },
  },
  chelsea: {
    name: "Chelsea",
    weights: {
      CB: { creativity: 15, threat: 15, influence: 25, productivity: 25, reliability: 20 },
      FB: { creativity: 25, threat: 15, influence: 15, productivity: 30, reliability: 15 },
      DM: { creativity: 15, threat: 10, influence: 30, productivity: 25, reliability: 20 },
      CM: { creativity: 25, threat: 20, influence: 20, productivity: 30, reliability: 5 },
      CAM: { creativity: 35, threat: 25, influence: 15, productivity: 30, reliability: 0 },
      WING: { creativity: 25, threat: 35, influence: 10, productivity: 35, reliability: 0 },
      ST: { creativity: 10, threat: 40, influence: 10, productivity: 40, reliability: 0 },
    },
  },
  barcelona: {
    name: "FC Barcelona",
    weights: {
      CB: { creativity: 30, threat: 0, influence: 35, productivity: 5, reliability: 30 },
      FB: { creativity: 40, threat: 0, influence: 25, productivity: 10, reliability: 25 },
      DM: { creativity: 30, threat: 0, influence: 40, productivity: 5, reliability: 30 },
      CM: { creativity: 40, threat: 5, influence: 30, productivity: 10, reliability: 15 },
      CAM: { creativity: 50, threat: 10, influence: 25, productivity: 10, reliability: 5 },
      WING: { creativity: 40, threat: 20, influence: 20, productivity: 15, reliability: 5 },
      ST: { creativity: 25, threat: 25, influence: 20, productivity: 20, reliability: 10 },
    },
  },
  realmadrid: {
    name: "Real Madrid",
    weights: {
      CB: { creativity: 5, threat: 20, influence: 40, productivity: 15, reliability: 20 },
      FB: { creativity: 15, threat: 20, influence: 30, productivity: 20, reliability: 15 },
      DM: { creativity: 5, threat: 15, influence: 45, productivity: 15, reliability: 20 },
      CM: { creativity: 15, threat: 25, influence: 35, productivity: 20, reliability: 5 },
      CAM: { creativity: 25, threat: 30, influence: 30, productivity: 20, reliability: 0 },
      WING: { creativity: 15, threat: 40, influence: 25, productivity: 25, reliability: 0 },
      ST: { creativity: 0, threat: 45, influence: 25, productivity: 30, reliability: 0 },
    },
  },
  bayern: {
    name: "Bayern Munich",
    weights: {
      CB: { creativity: 5, threat: 20, influence: 35, productivity: 15, reliability: 25 },
      FB: { creativity: 15, threat: 20, influence: 25, productivity: 20, reliability: 20 },
      DM: { creativity: 5, threat: 15, influence: 40, productivity: 15, reliability: 25 },
      CM: { creativity: 15, threat: 25, influence: 30, productivity: 20, reliability: 10 },
      CAM: { creativity: 25, threat: 30, influence: 25, productivity: 20, reliability: 0 },
      WING: { creativity: 15, threat: 40, influence: 20, productivity: 25, reliability: 0 },
      ST: { creativity: 0, threat: 45, influence: 20, productivity: 30, reliability: 5 },
    },
  },
  psg: {
    name: "Paris Saint-Germain",
    weights: {
      CB: { creativity: 25, threat: 0, influence: 35, productivity: 10, reliability: 30 },
      FB: { creativity: 35, threat: 0, influence: 25, productivity: 15, reliability: 25 },
      DM: { creativity: 25, threat: 0, influence: 40, productivity: 10, reliability: 30 },
      CM: { creativity: 35, threat: 5, influence: 30, productivity: 15, reliability: 15 },
      CAM: { creativity: 45, threat: 10, influence: 25, productivity: 15, reliability: 5 },
      WING: { creativity: 35, threat: 20, influence: 20, productivity: 20, reliability: 5 },
      ST: { creativity: 20, threat: 25, influence: 20, productivity: 25, reliability: 10 },
    },
  },
  juventus: {
    name: "Juventus FC",
    weights: {
      CB: { creativity: 15, threat: 0, influence: 40, productivity: 5, reliability: 40 },
      FB: { creativity: 25, threat: 0, influence: 30, productivity: 10, reliability: 35 },
      DM: { creativity: 15, threat: 0, influence: 45, productivity: 5, reliability: 40 },
      CM: { creativity: 25, threat: 5, influence: 35, productivity: 10, reliability: 25 },
      CAM: { creativity: 35, threat: 10, influence: 30, productivity: 10, reliability: 15 },
      WING: { creativity: 25, threat: 20, influence: 25, productivity: 15, reliability: 15 },
      ST: { creativity: 10, threat: 25, influence: 25, productivity: 20, reliability: 20 },
    },
  },
  dortmund: {
    name: "Borussia Dortmund",
    weights: {
      CB: { creativity: 5, threat: 20, influence: 30, productivity: 20, reliability: 25 },
      FB: { creativity: 15, threat: 20, influence: 20, productivity: 25, reliability: 20 },
      DM: { creativity: 5, threat: 15, influence: 35, productivity: 20, reliability: 25 },
      CM: { creativity: 15, threat: 25, influence: 25, productivity: 25, reliability: 10 },
      CAM: { creativity: 25, threat: 30, influence: 20, productivity: 25, reliability: 0 },
      WING: { creativity: 15, threat: 40, influence: 15, productivity: 30, reliability: 0 },
      ST: { creativity: 0, threat: 45, influence: 15, productivity: 35, reliability: 5 },
    },
  },
  intermilan: {
    name: "Inter Milan",
    weights: {
      CB: { creativity: 15, threat: 0, influence: 40, productivity: 5, reliability: 40 },
      FB: { creativity: 25, threat: 0, influence: 30, productivity: 10, reliability: 35 },
      DM: { creativity: 15, threat: 0, influence: 45, productivity: 5, reliability: 40 },
      CM: { creativity: 25, threat: 5, influence: 35, productivity: 10, reliability: 25 },
      CAM: { creativity: 35, threat: 10, influence: 30, productivity: 10, reliability: 15 },
      WING: { creativity: 25, threat: 20, influence: 25, productivity: 15, reliability: 15 },
      ST: { creativity: 10, threat: 25, influence: 25, productivity: 20, reliability: 20 },
    },
  },
};

export const PLAYERS: Record<PositionKey, Player[]> = {
  CB: [
    { name: "W. Saliba", cost: 100, stats: { creativity: 21, threat: 17, influence: 53, productivity: 25, reliability: 84 } },
    { name: "Virgil van Dijk", cost: 15, stats: { creativity: 34, threat: 57, influence: 88, productivity: 46, reliability: 96 } },
    { name: "Joško Gvardiol", cost: 70, stats: { creativity: 100, threat: 100, influence: 77, productivity: 58, reliability: 94 } },
    { name: "Rúben Dias", cost: 55, stats: { creativity: 26, threat: 24, influence: 27, productivity: 0, reliability: 50 } },
    { name: "Marc Guéhi", cost: 70, stats: { creativity: 41, threat: 45, influence: 74, productivity: 62, reliability: 84 } },
    { name: "Ezri Konsa", cost: 40, stats: { creativity: 15, threat: 28, influence: 35, productivity: 26, reliability: 79 } },
    { name: "Pau Torres", cost: 20, stats: { creativity: 6, threat: 14, influence: 11, productivity: 0, reliability: 40 } },
    { name: "Marcos Senesi", cost: 25, stats: { creativity: 6, threat: 0, influence: 0, productivity: 0, reliability: 0 } },
    { name: "Nathan Collins", cost: 30, stats: { creativity: 23, threat: 59, influence: 100, productivity: 100, reliability: 100 } },
    { name: "Ethan Pinnock", cost: 3, stats: { creativity: 10, threat: 34, influence: 36, productivity: 40, reliability: 35 } },
    { name: "Lewis Dunk", cost: 3.5, stats: { creativity: 13, threat: 19, influence: 20, productivity: 18, reliability: 42 } },
    { name: "Jan Paul van Hecke", cost: 45, stats: { creativity: 46, threat: 31, influence: 62, productivity: 26, reliability: 80 } },
    { name: "James Tarkowski", cost: 5, stats: { creativity: 30, threat: 39, influence: 78, productivity: 26, reliability: 79 } },
    { name: "Jarrad Branthwaite", cost: 40, stats: { creativity: 0, threat: 20, influence: 47, productivity: 15, reliability: 61 } },
    { name: "Calvin Bassey", cost: 28, stats: { creativity: 9, threat: 26, influence: 42, productivity: 12, reliability: 85 } },
    { name: "Joachim Andersen", cost: 20, stats: { creativity: 9, threat: 27, influence: 55, productivity: 0, reliability: 68 } },
    { name: "Wout Faes", cost: 10, stats: { creativity: 2, threat: 18, influence: 54, productivity: 14, reliability: 74 } },
  ],
  FB: [
    { name: "Gabriel Magalhães", cost: 75, stats: { creativity: 9, threat: 53, influence: 54, productivity: 50, reliability: 44 } },
    { name: "Trent Alexander-Arnold", cost: 60, stats: { creativity: 100, threat: 49, influence: 73, productivity: 100, reliability: 44 } },
    { name: "Marc Cucurella", cost: 50, stats: { creativity: 30, threat: 67, influence: 66, productivity: 55, reliability: 80 } },
    { name: "Milos Kerkez", cost: 35, stats: { creativity: 72, threat: 43, influence: 69, productivity: 57, reliability: 100 } },
    { name: "Matty Cash", cost: 22, stats: { creativity: 5, threat: 29, influence: 24, productivity: 23, reliability: 28 } },
    { name: "Lucas Digne", cost: 6, stats: { creativity: 64, threat: 18, influence: 45, productivity: 50, reliability: 44 } },
    { name: "Adam Smith", cost: 0.3, stats: { creativity: 0, threat: 0, influence: 0, productivity: 0, reliability: 0 } },
    { name: "Pervis Estupiñán", cost: 12, stats: { creativity: 56, threat: 30, influence: 44, productivity: 20, reliability: 46 } },
    { name: "Daniel Muñoz", cost: 22, stats: { creativity: 71, threat: 100, influence: 86, productivity: 73, reliability: 94 } },
    { name: "Tyrick Mitchell", cost: 25, stats: { creativity: 60, threat: 29, influence: 61, productivity: 46, reliability: 86 } },
    { name: "Vitalii Mykolenko", cost: 25, stats: { creativity: 41, threat: 15, influence: 59, productivity: 31, reliability: 85 } },
    { name: "Antonee Robinson", cost: 22, stats: { creativity: 84, threat: 36, influence: 100, productivity: 75, reliability: 90 } },
    { name: "James Justin", cost: 12, stats: { creativity: 16, threat: 36, influence: 59, productivity: 32, reliability: 76 } },
    { name: "Victor Kristiansen", cost: 9, stats: { creativity: 31, threat: 3, influence: 46, productivity: 10, reliability: 51 } },
    { name: "Keane Lewis-Potter", cost: 25, stats: { creativity: 46, threat: 73, influence: 49, productivity: 46, reliability: 86 } },
  ],
  DM: [
    { name: "Adam Wharton", cost: 70, stats: { creativity: 50, threat: 0, influence: 0, productivity: 74, reliability: 0 } },
    { name: "Idrissa Gueye", cost: 0.5, stats: { creativity: 36, threat: 33, influence: 71, productivity: 31, reliability: 86 } },
    { name: "Moisés Caicedo", cost: 100, stats: { creativity: 100, threat: 18, influence: 100, productivity: 71, reliability: 100 } },
    { name: "Ryan Gravenberch", cost: 80, stats: { creativity: 75, threat: 36, influence: 79, productivity: 54, reliability: 91 } },
    { name: "Carlos Baleba", cost: 55, stats: { creativity: 40, threat: 85, influence: 69, productivity: 72, reliability: 66 } },
    { name: "Amadou Onana", cost: 45, stats: { creativity: 1, threat: 100, influence: 26, productivity: 100, reliability: 15 } },
    { name: "Boubacar Kamara", cost: 40, stats: { creativity: 0, threat: 10, influence: 18, productivity: 0, reliability: 20 } },
    { name: "James Garner", cost: 45, stats: { creativity: 15, threat: 16, influence: 1, productivity: 4, reliability: 14 } },
  ],
  CM: [
    { name: "Alexis Mac Allister", cost: 70, stats: { creativity: 50, threat: 100, influence: 72, productivity: 100, reliability: 58 } },
    { name: "Youri Tielemans", cost: 30, stats: { creativity: 100, threat: 90, influence: 100, productivity: 64, reliability: 100 } },
    { name: "John McGinn", cost: 13, stats: { creativity: 0, threat: 61, influence: 0, productivity: 23, reliability: 21 } },
    { name: "Ryan Christie", cost: 8, stats: { creativity: 16, threat: 78, influence: 45, productivity: 27, reliability: 11 } },
    { name: "Lewis Cook", cost: 11, stats: { creativity: 49, threat: 0, influence: 63, productivity: 0, reliability: 95 } },
    { name: "Andreas Pereira", cost: 14, stats: { creativity: 80, threat: 77, influence: 9, productivity: 90, reliability: 0 } },
  ],
  CAM: [
    { name: "Cole Palmer", cost: 100, stats: { creativity: 86, threat: 100, influence: 100, productivity: 100, reliability: 100 } },
    { name: "Bruno Fernandes", cost: 35, stats: { creativity: 100, threat: 46, influence: 93, productivity: 80, reliability: 88 } },
    { name: "Martin Ødegaard", cost: 65, stats: { creativity: 57, threat: 35, influence: 24, productivity: 55, reliability: 42 } },
    { name: "Kevin De Bruyne", cost: 8, stats: { creativity: 53, threat: 26, influence: 16, productivity: 97, reliability: 0 } },
    { name: "Phil Foden", cost: 70, stats: { creativity: 36, threat: 30, influence: 13, productivity: 63, reliability: 5 } },
    { name: "Dominik Szoboszlai", cost: 100, stats: { creativity: 40, threat: 48, influence: 33, productivity: 76, reliability: 53 } },
    { name: "Morgan Rogers", cost: 90, stats: { creativity: 33, threat: 58, influence: 53, productivity: 71, reliability: 95 } },
    { name: "Justin Kluivert", cost: 25, stats: { creativity: 27, threat: 67, influence: 49, productivity: 98, reliability: 43 } },
    { name: "Eberechi Eze", cost: 65, stats: { creativity: 46, threat: 58, influence: 46, productivity: 72, reliability: 60 } },
    { name: "Abdoulaye Doucouré", cost: 5, stats: { creativity: 0, threat: 18, influence: 0, productivity: 0, reliability: 58 } },
    { name: "Emile Smith Rowe", cost: 20, stats: { creativity: 4, threat: 23, influence: 11, productivity: 42, reliability: 23 } },
    { name: "Bilal El Khannouss", cost: 35, stats: { creativity: 25, threat: 0, influence: 4, productivity: 14, reliability: 32 } },
  ],
  WING: [
    { name: "Mohamed Salah", cost: 22, stats: { creativity: 100, threat: 100, influence: 100, productivity: 100, reliability: 98 } },
    { name: "Bukayo Saka", cost: 110, stats: { creativity: 60, threat: 35, influence: 25, productivity: 66, reliability: 17 } },
    { name: "Antoine Semenyo", cost: 80, stats: { creativity: 42, threat: 56, influence: 40, productivity: 31, reliability: 90 } },
    { name: "Dango Ouattara", cost: 35, stats: { creativity: 21, threat: 31, influence: 27, productivity: 30, reliability: 31 } },
    { name: "Bryan Mbeumo", cost: 75, stats: { creativity: 90, threat: 48, influence: 74, productivity: 55, reliability: 100 } },
    { name: "Kevin Schade", cost: 35, stats: { creativity: 0, threat: 39, influence: 27, productivity: 39, reliability: 45 } },
    { name: "Kaoru Mitoma", cost: 22, stats: { creativity: 30, threat: 37, influence: 30, productivity: 32, reliability: 60 } },
    { name: "Yankuba Minteh", cost: 45, stats: { creativity: 15, threat: 23, influence: 19, productivity: 34, reliability: 23 } },
    { name: "Ismaïla Sarr", cost: 40, stats: { creativity: 34, threat: 37, influence: 31, productivity: 30, reliability: 65 } },
    { name: "Jack Harrison", cost: 6.5, stats: { creativity: 24, threat: 5, influence: 0, productivity: 0, reliability: 34 } },
    { name: "Dwight McNeil", cost: 18, stats: { creativity: 36, threat: 0, influence: 9, productivity: 57, reliability: 0 } },
    { name: "Alex Iwobi", cost: 20, stats: { creativity: 69, threat: 28, influence: 41, productivity: 26, reliability: 79 } },
    { name: "Adama Traoré", cost: 6, stats: { creativity: 36, threat: 12, influence: 8, productivity: 31, reliability: 19 } },
    { name: "Stephy Mavididi", cost: 8, stats: { creativity: 7, threat: 5, influence: 5, productivity: 10, reliability: 12 } },
    { name: "Iliman Ndiaye", cost: 55, stats: { creativity: 2, threat: 16, influence: 25, productivity: 15, reliability: 52 } },
  ],
  ST: [
    { name: "Georginio Rutter", cost: 30, stats: { creativity: 58, threat: 19, influence: 31, productivity: 53, reliability: 45 } },
    { name: "Erling Haaland", cost: 200, stats: { creativity: 77, threat: 100, influence: 100, productivity: 79, reliability: 92 } },
    { name: "Ollie Watkins", cost: 25, stats: { creativity: 73, threat: 73, influence: 79, productivity: 80, reliability: 86 } },
    { name: "Kai Havertz", cost: 55, stats: { creativity: 55, threat: 41, influence: 44, productivity: 51, reliability: 54 } },
    { name: "Nicolas Jackson", cost: 40, stats: { creativity: 79, threat: 61, influence: 54, productivity: 59, reliability: 70 } },
    { name: "Yoane Wissa", cost: 25, stats: { creativity: 86, threat: 76, influence: 89, productivity: 69, reliability: 100 } },
    { name: "Danny Welbeck", cost: 3, stats: { creativity: 70, threat: 39, influence: 54, productivity: 58, reliability: 65 } },
    { name: "Jean-Philippe Mateta", cost: 30, stats: { creativity: 88, threat: 48, influence: 68, productivity: 47, reliability: 88 } },
    { name: "Raúl Jiménez", cost: 3, stats: { creativity: 80, threat: 64, influence: 61, productivity: 47, reliability: 81 } },
    { name: "Rasmus Højlund", cost: 60, stats: { creativity: 51, threat: 21, influence: 12, productivity: 11, reliability: 60 } },
    { name: "Jhon Durán", cost: 15, stats: { creativity: 7, threat: 14, influence: 22, productivity: 100, reliability: 0 } },
    { name: "Evanilson", cost: 35, stats: { creativity: 70, threat: 60, influence: 43, productivity: 52, reliability: 74 } },
    { name: "João Pedro", cost: 80, stats: { creativity: 100, threat: 36, influence: 56, productivity: 69, reliability: 58 } },
    { name: "Dominic Calvert-Lewin", cost: 22, stats: { creativity: 20, threat: 31, influence: 13, productivity: 18, reliability: 43 } },
    { name: "Rodrigo Muniz", cost: 20, stats: { creativity: 13, threat: 26, influence: 31, productivity: 83, reliability: 14 } },
    { name: "Jamie Vardy", cost: 1, stats: { creativity: 55, threat: 44, influence: 47, productivity: 36, reliability: 96 } },
    { name: "Patson Daka", cost: 0.4, stats: { creativity: 0, threat: 0, influence: 0, productivity: 0, reliability: 4 } },
  ],
};
