import { Weights, Player } from "./scoring";

// Real 2024-25 Premier League season data (goals, assists, minutes,
// creativity, influence, threat, FPL price) — source: the public
// vaastav/Fantasy-Premier-League dataset, which mirrors the official
// Fantasy Premier League API. Used as the offline fallback pool of
// realistic transfer targets when Supabase isn't connected.
// Generated by generate-real-data.cjs — regenerate with
// `node generate-real-data.cjs` after editing the RAW stats above.
// See lib/supabaseClient.ts (isSupabaseConfigured) and lib/db.ts.

export const POSITIONS = {
  DEF: "Defender",
  MID: "Midfielder",
  FWD: "Forward",
} as const;

export type PositionKey = keyof typeof POSITIONS;

interface ClubDef {
  name: string;
  weights: Record<PositionKey, Weights>;
}

export const CLUBS: Record<string, ClubDef> = {
  arsenal: {
    name: "Arsenal",
    weights: {
      DEF: { creativity: 25, threat: 0, influence: 35, productivity: 10, reliability: 30 },
      MID: { creativity: 40, threat: 5, influence: 25, productivity: 15, reliability: 15 },
      FWD: { creativity: 20, threat: 25, influence: 20, productivity: 25, reliability: 10 },
    },
  },
  liverpool: {
    name: "Liverpool",
    weights: {
      DEF: { creativity: 5, threat: 20, influence: 35, productivity: 15, reliability: 25 },
      MID: { creativity: 20, threat: 25, influence: 25, productivity: 20, reliability: 10 },
      FWD: { creativity: 0, threat: 45, influence: 20, productivity: 30, reliability: 5 },
    },
  },
  mancity: {
    name: "Manchester City",
    weights: {
      DEF: { creativity: 30, threat: 0, influence: 35, productivity: 5, reliability: 30 },
      MID: { creativity: 45, threat: 5, influence: 25, productivity: 10, reliability: 15 },
      FWD: { creativity: 25, threat: 25, influence: 20, productivity: 20, reliability: 10 },
    },
  },
  manutd: {
    name: "Manchester United",
    weights: {
      DEF: { creativity: 5, threat: 20, influence: 30, productivity: 20, reliability: 25 },
      MID: { creativity: 20, threat: 25, influence: 20, productivity: 25, reliability: 10 },
      FWD: { creativity: 0, threat: 45, influence: 15, productivity: 35, reliability: 5 },
    },
  },
  chelsea: {
    name: "Chelsea",
    weights: {
      DEF: { creativity: 15, threat: 15, influence: 25, productivity: 25, reliability: 20 },
      MID: { creativity: 30, threat: 20, influence: 15, productivity: 30, reliability: 5 },
      FWD: { creativity: 10, threat: 40, influence: 10, productivity: 40, reliability: 0 },
    },
  },
};

export const PLAYERS: Record<PositionKey, Player[]> = {
  DEF: [
    { name: "W. Saliba", cost: 6.4, stats: { creativity: 0, threat: 0, influence: 43, productivity: 16, reliability: 72 } },
    { name: "Gabriel Magalhães", cost: 6.1, stats: { creativity: 9, threat: 45, influence: 23, productivity: 50, reliability: 9 } },
    { name: "Virgil van Dijk", cost: 6.7, stats: { creativity: 8, threat: 48, influence: 100, productivity: 28, reliability: 99 } },
    { name: "Trent Alexander-Arnold", cost: 7.2, stats: { creativity: 100, threat: 40, influence: 54, productivity: 100, reliability: 9 } },
    { name: "Joško Gvardiol", cost: 6.5, stats: { creativity: 51, threat: 100, influence: 81, productivity: 36, reliability: 95 } },
    { name: "Rúben Dias", cost: 5.5, stats: { creativity: 3, threat: 9, influence: 0, productivity: 0, reliability: 0 } },
    { name: "Marc Cucurella", cost: 5.4, stats: { creativity: 29, threat: 64, influence: 42, productivity: 55, reliability: 67 } },
    { name: "Marc Guéhi", cost: 4.7, stats: { creativity: 13, threat: 34, influence: 77, productivity: 39, reliability: 74 } },
    { name: "Milos Kerkez", cost: 5.3, stats: { creativity: 72, threat: 32, influence: 47, productivity: 57, reliability: 100 } },
  ],
  MID: [
    { name: "Mohamed Salah", cost: 13.6, stats: { creativity: 69, threat: 100, influence: 100, productivity: 100, reliability: 100 } },
    { name: "Cole Palmer", cost: 10.5, stats: { creativity: 78, threat: 43, influence: 55, productivity: 37, reliability: 89 } },
    { name: "Bruno Fernandes", cost: 8.4, stats: { creativity: 100, threat: 14, influence: 50, productivity: 25, reliability: 79 } },
    { name: "Bukayo Saka", cost: 10.4, stats: { creativity: 16, threat: 29, influence: 14, productivity: 58, reliability: 2 } },
    { name: "Martin Ødegaard", cost: 8.2, stats: { creativity: 35, threat: 8, influence: 7, productivity: 10, reliability: 37 } },
    { name: "Kevin De Bruyne", cost: 9.5, stats: { creativity: 28, threat: 3, influence: 2, productivity: 35, reliability: 0 } },
    { name: "Phil Foden", cost: 9.1, stats: { creativity: 3, threat: 6, influence: 0, productivity: 15, reliability: 5 } },
    { name: "Alexis Mac Allister", cost: 6.2, stats: { creativity: 0, threat: 0, influence: 18, productivity: 0, reliability: 54 } },
    { name: "Dominik Szoboszlai", cost: 6.1, stats: { creativity: 9, threat: 15, influence: 13, productivity: 23, reliability: 47 } },
  ],
  FWD: [
    { name: "Erling Haaland", cost: 14.9, stats: { creativity: 69, threat: 100, influence: 100, productivity: 98, reliability: 82 } },
    { name: "Ollie Watkins", cost: 9.2, stats: { creativity: 60, threat: 66, influence: 76, productivity: 100, reliability: 69 } },
    { name: "Kai Havertz", cost: 7.7, stats: { creativity: 9, threat: 26, influence: 37, productivity: 58, reliability: 0 } },
    { name: "Nicolas Jackson", cost: 7.7, stats: { creativity: 75, threat: 50, influence: 47, productivity: 70, reliability: 33 } },
    { name: "Yoane Wissa", cost: 6.9, stats: { creativity: 96, threat: 69, influence: 87, productivity: 85, reliability: 100 } },
    { name: "Danny Welbeck", cost: 5.5, stats: { creativity: 51, threat: 23, influence: 48, productivity: 68, reliability: 23 } },
    { name: "Jean-Philippe Mateta", cost: 7.5, stats: { creativity: 100, threat: 34, influence: 64, productivity: 53, reliability: 73 } },
    { name: "Raúl Jiménez", cost: 5.3, stats: { creativity: 78, threat: 54, influence: 56, productivity: 52, reliability: 59 } },
    { name: "Rasmus Højlund", cost: 6.9, stats: { creativity: 0, threat: 0, influence: 0, productivity: 0, reliability: 12 } },
  ],
};
